# Generated by Django 5.2.8 on 2026-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('allowance', models.FloatField()),
                ('deductions', models.FloatField()),
                ('pan_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
